version: "3.0"

services:
  server:
    build:
      context: .
    restart: always
    ports:
      - "7171:7171"
      - "7172:7172"
    depends_on:
      - db
    networks:
      - db-network
    volumes:
      - "mysql_socket:/var/run/mysqld/"
      - "./web:/var/www"
      - "//c/docker/server:/server"
			
	swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=yourdomain.url
      - SUBDOMAINS=www,
      - VALIDATION=http
      - DNSPLUGIN=cloudflare #optional
      - PROPAGATION= #optional
      - DUCKDNSTOKEN= #optional
      - EMAIL= #optional
      - ONLY_SUBDOMAINS=false #optional
      - EXTRA_DOMAINS= #optional
      - STAGING=false #optional
      - MAXMINDDB_LICENSE_KEY= #optional
    volumes:
      - //c/docker/swag:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
		
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: forgottenserver
      MYSQL_PASSWORD: password
      # Automatically creates a database
      MYSQL_DATABASE: forgottenserver
    volumes:
      # Saves all the data in ./db directory
      - //c/docker/mariadb:/var/lib/mysql
      # Automatically executes schema.sql on startup
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - "mysql_socket:/var/run/mysqld/"
    networks:
      - db-network

  db-adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - db-network
    volumes:
      - "mysql_socket:/var/run/mysqld/"		

networks:
  db-network:
volumes:
  mysql_socket:
  mysql_data:
